import Foundation

public enum AppStorageKeys {
    public static let mediaService = "\(Prefix.id).mediaService"
    public static let browseMediaService = "\(Prefix.id).browseMediaService"
    public static let appleMusicAuthorized = "\(Prefix.id).appleMusicAuthorized"
    public static let colorScheme = "\(Prefix.id).colorScheme"
    public static let speedLaunchNowPlaying = "\(Prefix.id).speedLaunchNowPlaying"
    public static let queueMode = "\(Prefix.id).queueMode"
    public static let showArtworkOnly = "\(Prefix.id).showArtworkOnly"
    public static let queueInspectorVisible = "\(Prefix.id).queueInspectorVisible"
    public static let savedGroupID = "\(Prefix.id).queueInspectorGroupID"
    public static let defaultPlayAction = "\(Prefix.id).defaultPlayAction"
    public static let lastPlaylistID = "\(Prefix.id).lastPlaylistID"
    public static let lastPlaylistTitle = "\(Prefix.id).lastPlaylistTitle"
    public static let lastPlaylistService = "\(Prefix.id).lastPlaylistService"
    public static let addToPlaylistSegment = "\(Prefix.id).addToPlaylistSegment"
    public static let recentlyViewed = "\(Prefix.id).recentlyViewed"
    public static let recentQueries = "\(Prefix.id).recentQueries"
    public static let lastSeenWhatsNewVersion = "\(Prefix.id).lastSeenWhatsNewVersion"
    public static let lastSeenSettingsBadgeVersion = "\(Prefix.id).lastSeenSettingsBadgeVersion"
    public static let latestReleaseVersion = "\(Prefix.id).latestReleaseVersion"
    public static let latestReleaseHeadline = "\(Prefix.id).latestReleaseHeadline"
    public static let useHardwareVolumeButtons = "\(Prefix.id).useHardwareVolumeButtons"
}
